version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
  - cmd: SET PATH=C:\Ruby26-x64\bin;%PATH%
  - cmd: ruby --version
  - cmd: git --version
build_script:
  - bundle update
  - bundle install
test_script:
  - git config --global user.email "server@0pdd.com"
  - git config --global user.name "0pdd.com"
  - rake
cache:
  - C:\Ruby200\bin -> pdd.gemspec
  - C:\Ruby200\lib\ruby\gems\2.0.0 -> pdd.gemspec
